name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Build Docker Image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/infra-lab:latest .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/infra-lab:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy infra-lab \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/infra-lab:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
